apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysopexapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sysopExapp
  template:
    metadata:
      labels:
        app: sysopExapp
    spec:


      containers:
      - name: app
        image: sysopex123.azurecr.io/sysopexapp:v1



        ports:
        - containerPort: 8000
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASS

          - name: AZURE_STORAGE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: blob-secret
                key: AZURE_STORAGE_CONNECTION_STRING

        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
